resources:
  - name: api-student-5
    type: git
    source:
      uri: https://github.com/asy8165/api-student-5
      branch: master
    check_every: 10s
jobs:
- name: unit-test
  plan:
  - get: api-student-5
    trigger: true
  - task: mvn-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
      inputs:
      - name: api-student-5
      caches:
      - path: api-student-5/m2   
      run:
        path: bash
        args:
        - -c
        - |
          set -e
          cd api-student-5
          rm -rf ~/.m2
          ln -fs $(pwd)/m2 ~/.m2
          mvn test